/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=r2-container/wrangler.jsonc --include-runtime=false r2-container/worker-configuration.d.ts` (hash: d2972ff90c585672a2acbefd08e84ddb)
interface __BaseEnv_Env {
	R2_ENDPOINT: "https://REPLACE_ACCOUNT_ID.r2.cloudflarestorage.com";
	LISTING_ID: "synthetic-listing";
	LISTING_VERSION_ID: "synthetic-v1";
	SPIKE_SPEC_PUBLIC_KEY_B64: "";
	SCANNER: DurableObjectNamespace<import("./index").Scanner>;
	LEDGER: DurableObjectNamespace<import("./index").Ledger>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Scanner" | "Ledger";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_ENDPOINT" | "LISTING_ID" | "LISTING_VERSION_ID" | "SPIKE_SPEC_PUBLIC_KEY_B64">> {}
}
