#!/usr/bin/env python3
"""Render the frozen gateway-to-ai.market examples from the golden vectors."""
import json
from pathlib import Path
import sys

TYPES = ("hello", "inventory", "description", "receipt", "canary_result",
         "revocation_ack", "offer_ack", "prepare_ack", "error")
OUTPUT = Path("docs/outbound-messages.md")


def render() -> str:
    lines = ["# Gateway to ai.market messages", "", "Generated by `python3 scripts/gen-outbound-doc.py` from the valid golden vectors.",
             "Examples are synthetic test data. The local signed audit log records each outbound body.", ""]
    for name in TYPES:
        vector = json.loads((Path("contract/vectors") / f"{name}.json").read_text())
        if vector.get("expected_verdict") != "valid" or not isinstance(vector.get("input"), dict):
            raise ValueError(f"missing valid input for {name}")
        lines.extend((f"## `{name}`", "", "```json", json.dumps(vector["input"], indent=2, sort_keys=True), "```", ""))
    lines.extend(("## `scan_report`", "", "Identity-key audit envelope; successful, terminal and probe receipts use the separate local receipt key.",
                  "Decoded documents are Python-canonical JSON (700 KiB maximum); the whole audit frame remains at most 1 MiB.", ""))
    for name in ("registration", "probe_report", "scan_report", "terminal_report"):
        vector = json.loads((Path("contract/vectors/verification") / f"{name}.json").read_text())
        if name == "registration":
            body = vector["input"]
        else:
            import base64
            body = {"op": "scan_report", "variant": {"probe_report": "probe", "scan_report": "scan", "terminal_report": "terminal"}[name],
                    "runner_id": "66666666-6666-4666-8666-666666666666", "iid": "88888888-8888-4888-8888-888888888888",
                    "document_b64": base64.urlsafe_b64encode(vector["canonical"].encode()).decode().rstrip("=")}
        lines.extend((f"### `{name}`", "", "```json", json.dumps(body, indent=2, sort_keys=True), "```", ""))
    return "\n".join(lines)


if __name__ == "__main__":
    try:
        contents = render()
        if sys.argv[1:] == ["--check"]:
            if not OUTPUT.exists() or OUTPUT.read_text() != contents:
                raise ValueError("generated document is stale")
            print("outbound messages: current")
        elif not sys.argv[1:]:
            OUTPUT.parent.mkdir(exist_ok=True)
            OUTPUT.write_text(contents)
        else:
            raise ValueError("usage: gen-outbound-doc.py [--check]")
    except (OSError, ValueError) as error:
        sys.exit(f"outbound messages: {error}")
