/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=RuntimeEnv` (hash: ae60e89842f4cb35f6064d779321646d)
interface __BaseEnv_RuntimeEnv {
	SOURCE: R2Bucket;
	DEPLOYMENT_CONFIG: "{}";
	VERIFIER: DurableObjectNamespace /* CloudflareVerifier */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_RuntimeEnv {}
}
interface RuntimeEnv extends __BaseEnv_RuntimeEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_CONFIG">> {}
}
